
variables:

  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true


  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

image: maven:3-openjdk-17

cache:
  paths:
    - .m2/repository

checkStyle:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS checkstyle:check'


unit-test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'


code-coverage:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS jacoco:prepare-agent test jacoco:report'
    - 'mvn $MAVEN_CLI_OPTS verify --settings ci_settings.xml'
  artifacts:
    paths:
      - target/site/jacoco/
  dependencies:
    - unit-test


maven-build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS compile"




